[2021-06-14 12:49:15,280] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_is_trip_based 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 12:49:15,409] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_is_trip_based 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 12:49:15,410] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 12:49:15,410] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-14 12:49:15,410] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 12:49:15,478] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): queue_is_trip_based> on 2021-06-13T00:00:00+00:00
[2021-06-14 12:49:15,606] {standard_task_runner.py:52} INFO - Started process 408 to run task
[2021-06-14 12:49:15,640] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'queue_is_trip_based', '2021-06-13T00:00:00+00:00', '--job-id', '50', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpxmmibk8r', '--error-file', '/tmp/tmprca46j69']
[2021-06-14 12:49:15,668] {standard_task_runner.py:77} INFO - Job 50: Subtask queue_is_trip_based
[2021-06-14 12:49:16,147] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.queue_is_trip_based 2021-06-13T00:00:00+00:00 [running]> on host 7874826b9cd7
[2021-06-14 12:49:16,718] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=queue_is_trip_based
AIRFLOW_CTX_EXECUTION_DATE=2021-06-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-13T00:00:00+00:00
[2021-06-14 12:49:16,719] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-14 12:49:29,749] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-14 12:49:29,838] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/io/sql.py:1423 UserWarning: The provided table name '21N_queue_is_trip_based' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2021-06-14 12:49:29,839] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-14 12:49:29,841] {python.py:151} INFO - Done. Returned value was: None
[2021-06-14 12:49:29,854] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=queue_is_trip_based, execution_date=20210613T000000, start_date=20210614T124915, end_date=20210614T124929
[2021-06-14 12:49:29,897] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-14 12:49:29,936] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-06-14 15:28:31,495] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_is_trip_based 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 15:28:31,855] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_is_trip_based 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 15:28:31,856] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 15:28:31,856] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-14 15:28:31,856] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 15:28:32,101] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): queue_is_trip_based> on 2021-06-13T00:00:00+00:00
[2021-06-14 15:28:32,172] {standard_task_runner.py:52} INFO - Started process 838 to run task
[2021-06-14 15:28:32,217] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'queue_is_trip_based', '2021-06-13T00:00:00+00:00', '--job-id', '89', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp7cv3iivt', '--error-file', '/tmp/tmpth_fcdrf']
[2021-06-14 15:28:32,218] {standard_task_runner.py:77} INFO - Job 89: Subtask queue_is_trip_based
[2021-06-14 15:28:33,137] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.queue_is_trip_based 2021-06-13T00:00:00+00:00 [running]> on host 7874826b9cd7
[2021-06-14 15:28:34,291] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=queue_is_trip_based
AIRFLOW_CTX_EXECUTION_DATE=2021-06-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-13T00:00:00+00:00
[2021-06-14 15:28:34,343] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-14 15:28:46,013] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-14 15:28:46,528] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/io/sql.py:1423 UserWarning: The provided table name '21N_queue_is_trip_based' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2021-06-14 15:28:46,528] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-14 15:28:46,529] {python.py:151} INFO - Done. Returned value was: None
[2021-06-14 15:28:46,681] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=queue_is_trip_based, execution_date=20210613T000000, start_date=20210614T152831, end_date=20210614T152846
[2021-06-14 15:28:47,022] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-14 15:28:47,074] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-06-14 18:34:28,694] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_is_trip_based 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 18:34:29,151] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_is_trip_based 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 18:34:29,153] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 18:34:29,154] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-14 18:34:29,155] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 18:34:29,344] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): queue_is_trip_based> on 2021-06-13T00:00:00+00:00
[2021-06-14 18:34:29,505] {standard_task_runner.py:52} INFO - Started process 298 to run task
[2021-06-14 18:34:29,719] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'queue_is_trip_based', '2021-06-13T00:00:00+00:00', '--job-id', '118', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp1axma5oi', '--error-file', '/tmp/tmp_67zltw4']
[2021-06-14 18:34:29,815] {standard_task_runner.py:77} INFO - Job 118: Subtask queue_is_trip_based
[2021-06-14 18:34:30,482] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.queue_is_trip_based 2021-06-13T00:00:00+00:00 [running]> on host 89c270a4555f
[2021-06-14 18:34:31,275] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=queue_is_trip_based
AIRFLOW_CTX_EXECUTION_DATE=2021-06-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-13T00:00:00+00:00
[2021-06-14 18:34:31,288] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-14 18:34:47,775] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-14 18:34:48,181] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/io/sql.py:1423 UserWarning: The provided table name '21N_queue_is_trip_based' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2021-06-14 18:34:48,185] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-14 18:34:48,185] {python.py:151} INFO - Done. Returned value was: None
[2021-06-14 18:34:48,341] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=queue_is_trip_based, execution_date=20210613T000000, start_date=20210614T183428, end_date=20210614T183448
[2021-06-14 18:34:48,748] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-14 18:34:48,785] {local_task_job.py:151} INFO - Task exited with return code 0
