[2021-06-15 17:51:14,113] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_state 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 17:51:14,210] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_state 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 17:51:14,210] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 17:51:14,211] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-15 17:51:14,211] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 17:51:14,280] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): queue_state> on 2021-06-14T00:00:00+00:00
[2021-06-15 17:51:14,343] {standard_task_runner.py:52} INFO - Started process 963 to run task
[2021-06-15 17:51:14,403] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'queue_state', '2021-06-14T00:00:00+00:00', '--job-id', '143', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpopr84b6u', '--error-file', '/tmp/tmpcl8whadr']
[2021-06-15 17:51:14,404] {standard_task_runner.py:77} INFO - Job 143: Subtask queue_state
[2021-06-15 17:51:14,711] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.queue_state 2021-06-14T00:00:00+00:00 [running]> on host bb8bb196dd92
[2021-06-15 17:51:15,149] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=queue_state
AIRFLOW_CTX_EXECUTION_DATE=2021-06-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-14T00:00:00+00:00
[2021-06-15 17:51:15,151] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-15 17:51:39,118] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-15 17:51:58,518] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/io/sql.py:1423 UserWarning: The provided table name '21N_queue_state' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2021-06-15 17:51:58,521] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-15 17:51:58,898] {python.py:151} INFO - Done. Returned value was: None
[2021-06-15 17:51:59,192] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=queue_state, execution_date=20210614T000000, start_date=20210615T175114, end_date=20210615T175159
[2021-06-15 17:51:59,394] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-15 17:51:59,454] {local_task_job.py:151} INFO - Task exited with return code 0
